Add PHP 8.0 support to composer.json
Sylius/SyliusAdminApiBundle pull request #7
Opened 2021-06-30 07:15 UTC by sasa-b

2021-06-30 13:57 UTC, pamil requested changes
Could you add PHP 8.0 build to GitHub Actions? https://github.com/Sylius/SyliusAdminApiBundle/blob/master/.github/workflows/build.yml#L24

2021-06-30 15:33 UTC, sasa-b commented
@pamil I've added the PHP 8.0 in the github build.yaml and I've also bumped the Sylius version to ~1.10.0 there as the Admin Api has been extracted to a separate bundle in that version.

2021-07-29 06:59 UTC, dsbe-ak commented
Any updates? How can I run the api v1 with php 8?

2021-07-29 08:03 UTC, sasa-b commented
@dsbe-ak  I've forked this bundle and use the fork for the time being https://github.com/sasa-b/SyliusAdminApiBundle. After updating the gitflow build file as requested it is failing now and I don't have time to dig deeper.

2021-08-10 08:43 UTC, dsbe-ak commented
So this is only failing because of test "CustomerApiTest::it_returns_page_not_found_if_limit_is_set_to_0", correct?
In my opinion this has nothing to do with the update to php 8.0 (test is also failing for php 7.4).

Is this test method necessary at all?

Thanks

2021-08-24 08:18 UTC, AdamKasp commented
replaced with #10

2021-08-24 08:18 UTC, closed without merging